services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: LearnTogether/LearnTogether.API/Dockerfile
    ports:
      - "5000:80"  
    environment:
      Jwt__Issuer:  "https://learn-together.xyz/api/"
      Jwt__Audience: "https://learn-together.xyz:3000"
      Jwt__Key: "oLJq@9XnC!h*H4nCz#^b1W~nKJg%Mj@5^rSz6w@p"
      ConnectionStrings__Default: "Host=postgres;Database=LearnTogetherDb;Username=postgres;Password=LearnTogetherPassword"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15  
    environment:        
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: LearnTogetherPassword 
      POSTGRES_DB: LearnTogetherDb    
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/certbot
    depends_on:
      - frontend
      - backend
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 5; done'"
volumes:
  db_data: 
