export const mockUsers = [
  {
    id: 1,
    name: 'Расин Олег',
    speciality: 'Кандидат физико-математических наук',
    group: '',
    rating: "genius",
    subjects: ['math'],
    skills: ['Алгебра', 'Дискретная математика', 'Геометрия'],
    photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUaI1VJbaD3QI3Yd_EhIHOEkvU9v83NpdEbdVxfx6iUXgfyt9cDsc_4ttCjv_glEovRvU&usqp=CAU',
    telegram: 'oI_Io_P'
  },
  {
    id: 2,
    name: 'Иван Иванов',
    speciality: 'ФИИТ',
    group: 'ФТ-203',
    rating: "newbie",
    subjects: ['programming'],
    skills: ['C#', 'ASP.NET', 'PostgreSQL', 'Python'],
    photo: 'https://via.placeholder.com/150',
  },
  {
    id: 3,
    name: 'Иван Иванов',
    speciality: 'ФИИТ',
    group: 'ФТ-203',
    rating: "newbie",
    subjects: ['programming'],
    skills: ['C#', 'ASP.NET', 'PostgreSQL', 'Python'],
    photo: 'https://via.placeholder.com/150',
  },
  {
    id: 4,
    name: 'Иван Иванов',
    speciality: 'ФИИТ',
    group: 'ФТ-203',
    rating: "newbie",
    subjects: ['programming'],
    skills: ['C#', 'ASP.NET', 'PostgreSQL', 'Python'],
    photo: 'https://via.placeholder.com/150',
  },
  {
    id: 5,
    name: 'Иван Иванов',
    speciality: 'ФИИТ',
    group: 'ФТ-203',
    rating: "newbie",
    subjects: ['programming'],
    skills: ['C#', 'ASP.NET', 'PostgreSQL', 'Python'],
    photo: 'https://via.placeholder.com/150',
  }
]