const post = {
  id: "1",
  userId: "123",
  userName: "Иван Иванов",
  requiredSubject: "Математика",
  helpSubjects: ["Физика", "Информатика"],
  description: "Готов помочь с подготовкой к экзаменам",
  photo: "placeholder.png",
};

export const mockPosts = [
  {
    userId: "123",
    userName: "Иван Иванов",
    requiredSubject: "Math",
    helpSubjects: ["CSharp", "Algorithms"],
    description: "Готов помочь с подготовкой к экзаменам",
    photo: "placeholder.png",
    speciality: 'ФИИТ',
    group: 'ФТ-203',
    login: 'oI_Io_P',
    rating: 1,
  },
  {
    userId: "189274",
    userName: "Дмитрий Хлопин",
    requiredSubject: "CSharp",
    helpSubjects: ["Probability", "Algorithms", "MachineLearning"],
    description: "Тервре это я, тервер это мы",
    photo: "placeholder.png",
    speciality: 'Доцент',
    group: '',
    login: 'X_V_I_M',
    rating: 10,
  },
  {
    userId: "658543",
    userName: "Рас Олегов",
    requiredSubject: "MachineLearning",
    helpSubjects: ["Math", "DataStructures"],
    description: "Очевидно, но не все",
    photo: "placeholder.png",
    speciality: 'Доцент, кандидат физико-математических наук',
    group: '',
    login: 'RasinOleg',
    rating: 10,
  },
  {
    userId: "986736",
    userName: "Зюк Михайлов",
    requiredSubject: "Algorithms",
    helpSubjects: ["Math", "Probability", "CSharp", "MachineLearning", "DataStructures"],
    description: "всегда готов помочь",
    photo: "placeholder.png",
    speciality: 'ФИИТ',
    group: 'ФТ-203',
    login: '',
    rating: 4.9
  },
  {
    userId: "346733",
    userName: "Мария Петрова",
    requiredSubject: "MachineLearning",
    helpSubjects: ["Math", "Probability"],
    description: "Могу помочь разобраться с теорией вероятностей и математическим анализом",
    photo: "placeholder.png",
    rating: 3.9,
    speciality: 'Алгобак',
    group: '',
    login: '',
  },
  {
    userId: "333789",
    userName: "Радик Черепанов",
    requiredSubject: "Probability",
    helpSubjects: ["Algorithms", "CSharp"],
    description: "Объясню, как работают алгоритмы и структуры данных",
    photo: "placeholder.png",
    rating: 1.2,
    speciality: 'ФИИТ',
    group: 'ФТ-401',
    login: '',
  }
]